### ISSUE TITLE
Monster-card exclusion not working with filter.options

### ISSUE THREAD

**Issue by ciotlosm** [ciotlosm/custom-lovelace#105]
Using the config below with some automations sharing the name will result in exclusion not being applied correctly.

```yaml
      - type: custom:monster-card
        filter:
          include:
            - name: '*bedroom*'
               options:
                 secondary_info: last-changed
            - name: '*bedside*'
          exclude:
            - domain: automation
        card:
          type: entities
          title: Bedroom
          show_header_toggle: false
```

Probably due to #45 

cc: @minchik
