### ISSUE TITLE
Thermo card does not work properly as a custom card on picture-elements card

### ISSUE THREAD

**Issue by arsaboo** [ciotlosm/custom-lovelace#129]
I was hoping to use the thermo card on picture-elements card to display the current temperature. I added the following config:
```yaml
          - type: custom:thermostat-card
            entity: climate.bedroom
            hvac:
              attribute: operation
            style:
              top: 20%
              left: 45%
              width: 50px
              height: 50px
```
and here's the output:
![image](https://user-images.githubusercontent.com/18319734/43296113-5315df84-9117-11e8-98a7-78d35529a9ee.png)

The white border around the thermostat should not appear. I have tried a few other custom-cards (see [here](https://github.com/arsaboo/homeassistant-config/blob/master/www/custom_ui/circle-sensor-card.js) for an example) and they don't have such borders.

**Comment by ciotlosm** [comment]
Try using `no_card: true` parameter that is now available. If happy with implementation, please close the item

**Comment by arsaboo** [comment]
Thanks....it mostly fixes the issue. But, there may be another bug here. I tried 
```yaml
          - type: custom:thermostat-card
            entity: climate.downstairs
            no_card: true
            hvac:
              attribute: operation
            style:
              top: 20%
              left: 45%
              width: 50px
              height: 50px
              font-size: 90px
```
I was hoping that `font-size` will change the size of the temp. Instead it moves the position of the thermostat on the card and does not change the font-size. It is not a major issue, but just thought of highlighting the same.
