### ISSUE TITLE
entity-attributes-card.js throws an error

### ISSUE THREAD

**Issue by rrubin0** [ciotlosm/custom-lovelace#136]
Home assistant version: 0.74.2
Frontend JS version: "latest"

Error:
`2018-07-29 22:46:17 ERROR (MainThread) https://hassio/local/lovelace_cards/entity-attributes-card.js?v=1:4:30 Uncaught SyntaxError: Unexpected string`

Config (UI Lovelace):
```
resources:
  - url: /local/lovelace_cards/entity-attributes-card.js
    type: js

title: Home
views:
  - title: Lab
    icon: mdi:test-tube
    cards:
      - type: entities
        title: Away Timer
        show_header_toggle: false
        entities:
          - timer.away_mode
          - type: custom:entity-attributes-card
            entity: timer.away_mode
            filter:
              include:
                - timer.away_mode.duration
                - timer.away_mode.remaining
          - script.start_away_timer
          - script.pause_away_timer
          - script.cancel_away_timer
          - script.finish_away_timer
```
Notes:
I am already using monster card, gauge card, and animated weather card; these are working just fine. This one errors out on me for some reason.
