### ISSUE TITLE
Gauge Card severity colors and themes

### ISSUE THREAD

**Issue by VDRainer** [ciotlosm/custom-lovelace#141]
With the HA default theme the colors of the gauge card show as expected.
![auswahl_137](https://user-images.githubusercontent.com/26381449/43486805-093e9052-9515-11e8-9abc-b14bbc7f9334.png)

With a dark theme:
![auswahl_138](https://user-images.githubusercontent.com/26381449/43486832-20c06a20-9515-11e8-84c4-6f7adc1e6fc3.png)

Config:
```
        cards:
          - type: custom:gauge-card
            title: Temperature
            entity: sensor.aussen_temp
            min: -20
            max: 40
            scale: '40px'
            severity:
              red: 28
              green: 0
              amber: 21

          - type: custom:gauge-card
            title: Humidity
            entity:  sensor.aussen_humi
            min: 0
            max: 100
            scale: '40px'
            severity:
              red: 60
              green: 0
              amber: 50
```
