### ISSUE TITLE
Group-card not loading when switching tabs

### ISSUE THREAD

**Issue by Boosik** [ciotlosm/custom-lovelace#143]
Hi,
when I first load (or reload with F5) a tab with group card, it loads properly, however when I change to another tab and back, group cards are not loaded.

First load (or F5) on SYSTEM tab: https://i.imgur.com/mBvruUl.png
After clicking on HOME tab and then back on SYSTEM tab: https://i.imgur.com/alMTjUi.png

Reproduction rate is 100%, cards are using group.all_automations and group.all_switches.
There isn't any error in chrome developer JS console.

My tabs configuration:
```
view:
  - title: Home
    (... my HOME tab config ...)
  - title: System
    cards:
      - type: entities
        title: "Systemov\xE9 informace"
        show_header_toggle: true
        entities:
          - sensor.uptime
          - sensor.load_1m
          - sensor.load_5m
          - sensor.load_15m
          - sensor.processor_use
          - sensor.memory_use_percent
          - sensor.swap_use_percent
      - type: custom:group-card
        card:
          type: entities
          title: Automatizace
        group: group.all_automations
      - type: custom:group-card
        card:
          type: entities
          title: Přepínače
        group: group.all_switches
```
