### ISSUE TITLE
Attributes card - allow custom attribute name and entity source

### ISSUE THREAD

**Issue by ciotlosm** [ciotlosm/custom-lovelace#15]
Attributes card allow more custom approach:

```yaml
- type: custom:entity-attributes-card
  title: Attributes Card
  attributes:
    - key: media_player.bedroom.attributes.app_name
      name: Application
    - key: media_player.bedroom.attributes.media_title
      name: Media center
    - key: climate.bedroom.attributes.current_temperature
      name: Bedroom TV
```
