### ISSUE TITLE
Allow monster card when conditions similar to automation conditions

### ISSUE THREAD

**Issue by philhawthorne** [ciotlosm/custom-lovelace#157]
It might be good for the monster card to support the ability to show its elements based on multiple sets of criteria.

For consistency with Home Assistant, it might be better to try use the same style conditions have.

```yaml
- type: custom:monster-card
  card:
    - type: glance
  filter:
    include:
      - entity_id: alarm_control_panel.alarm
  when:
    # Only show when people are away, AND the arm panel is armed
    when: and
    conditions:
      - when: state
        entity_id: alarm_control_panel.ha_alarm
        state: 'armed_away'
      - when: state
        entity_id: 'group.people'
        state: 'not_home'
```

```yaml
- type: custom:monster-card
  card:
    - type: glance
  filter:
    include:
      - entity_id: alarm_control_panel.alarm
  when:
    # Show when people are away OR the arm panel is disarmed
    when: or
    conditions:
      - when: state
        entity_id: alarm_control_panel.ha_alarm
        state: 'disarmed'
      - when: state
        entity_id: 'group.people'
        state: 'not_home'
```
