### ISSUE TITLE
Implement show_header_toggle on monster-card

### ISSUE THREAD

**Issue by kylerw** [ciotlosm/custom-lovelace#16]
According to docs, `show_header_toggle` on monster-card not available at the moment

**Comment by magnusoverli** [comment]
I´d like to +1 this request.

Fantastic work on the monster-card! A real timesaver!!

**Comment by ciotlosm** [comment]
@kylerw Are you using it with entities or glance? Entities card should get the header by default.

**Comment by kylerw** [comment]
Doesn't appear to be


```
      - type:  "custom:monster-card"
        show_header_toggle: false
        card:
          title: Docker
          type: entities
        filter:
          include:
            - domain: switch
              entity_id: '*docker_*'
```

Is one example of where I am using it.

**Comment by ciotlosm** [comment]
`show_header_toggle: false` should be `show_header_toggle: true` or removed completely.

Or maybe I don't understand it properly. If you actually want to remove header toggle you'd be doing:

```yaml
      - type:  "custom:monster-card"
        
        card:
          title: Docker
          type: entities
          show_header_toggle: false
        filter:
          include:
            - domain: switch
              entity_id: '*docker_*'
```
