### ISSUE TITLE
Example of state filter for monster card

### ISSUE THREAD

**Issue by mihalski** [ciotlosm/custom-lovelace#166]
Hi,

Perhaps adding an example of a state filter to the monster-card page would be helpful for some people?
I had a lot of difficulty with this basic filter (for reasons unknown. I suspect I excluded it from the list of possibilities due to some typo or formatting error on my part).

```yaml
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: Lights On
        filter:
          include:
            - domain: light
              state: 'on'
```
Eventually @jeradM in #lovelace on the Discord suggested the above which

Regards,
Michal

P.S. @dale3h suggested a different approach which could also be illustrative in that it covers multiple states in the exclusion.
```yaml
      - type: custom:monster-card
        show_empty: false
        card:
          type: glance
          title: Lights On
        filter:
          include:
            - domain: light
          exclude:
            - state: 'off'
            - state: 'unavailable'
```
