### ISSUE TITLE
Allow calculation within filter/state

### ISSUE THREAD

**Issue by kylerw** [ciotlosm/custom-lovelace#17]
Example:

```yaml
    - type: "custom:monster-card"
        show_empty: false
        card:
          title: Low Battery
          show_header_toggle: false
        filter:
          include:
            - domain: sensor
              entity_id: '*battery*' 
              state: < 20     
```
