### ISSUE TITLE
Group Card not working, group-card.js?v=1:19 Uncaught TypeError: Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by phdelodder** [ciotlosm/custom-lovelace#183]
```
- title: Batteries
     icon: mdi:battery-alert
     cards:
       - type: custom:group-card
         card:
           type: entities
           title: Alert
         group: group.battery_alert
       - type: custom:group-card
         card:
           type: entities
           title: Status
         group: group.battery_status
```

```
group-card.js?v=1:19 Uncaught TypeError: Cannot read property 'attributes' of undefined
    at HTMLElement.set hass [as hass] (group-card.js?v=1:19)
    at t.cards.map.t (hui-view.js:132)
    at Array.map (<anonymous>)
    at HTMLElement._createCards (hui-view.js:130)
    at Object.D [as fn] (property-effects.js:815)
    at x (property-effects.js:159)
    at w (property-effects.js:125)
    at HTMLElement._propertiesChanged (property-effects.js:1707)
    at HTMLElement._flushProperties (properties-changed.js:335)
    at HTMLElement._flushProperties (property-effects.js:1555)
```
