### ISSUE TITLE
n.setConfig is not a function

### ISSUE THREAD

**Issue by ppmt** [ciotlosm/custom-lovelace#184]
I am using HomeAssistant rev 0.76.2

I have seen the FAQ regarding an errotr with n.setConfig but mine is different. I am using plan-coordinates and when I load the view I get this error in red
```
n.setConfig is not a function

{
 "type": "custom:plan-coordinates"
}
```
The coordinate box doesn't display.

Here the code I use in ui-lovelace.yaml

```
  - title: FloorPlan
    icon: mdi:home-heart
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:plan-coordinates
          - type: picture-elements
            image: /local/floorplan.png
            elements:
              - type: state-icon
                tap_action: toggle
                entity: light.sofa_lamp
                style:
                  top: 75%
                  left: 32%
              - type: state-icon
                tap_action: toggle
                entity: light.tv_lamp
                icon: mdi:lamp
                style:
                  top: 37%
                  left: 29%
```
