### ISSUE TITLE
Suggestion: Monster Card to Filter by device class

### ISSUE THREAD

**Issue by fortepc** [ciotlosm/custom-lovelace#199]
Adding the ability to filter by device class would make cards like these able to be better. Being able to specify all devices that are specific device_class would make it so we wouldn't have to rely on a entity naming scheme. battery sensors, window sensors, we already class them to make them appear in the UI correctly, it would be nice to be able to lean on these to make our monster cards easier. 

```yaml
      - type: custom:monster-card
        show_empty: false
        card:
          type: glance
          title: Low Battery Devices
        filter:
          include:
            - entity_id: "*battery_level*"
              state: '< 25'
            - attributes:
                battery: '< 25'
            - attributes:
                battery_level: '< 25'
```

```yaml
  - title: Kitchen
    cards:
      - type: custom:monster-card
        show_empty: false
        card:
          type: glance
          title: Open Windows
        filter:
          include:
            - entity_id: "*kitchen*window*"
              domain: binary_sensor
              state: on

**Comment by ciotlosm** [comment]
@fortepc Can you post a config on what you had in mind? It would help out to see how you think the config should look so I can think of how this could be implemented. Sounds like a good idea.

**Comment by fortepc** [comment]
Sure can! I will have to remember to do that when I get home.

**Comment by fortepc** [comment]
Battery Warning card

```yaml
      - type: custom:monster-card
        show_empty: false
        card:
          type: glance
          title: Low Battery Devices
        filter:
          include:
            - device_class: battery
              state: '< 25'
            - attributes:
                battery: '< 25'
            - attributes:
                battery_level: '< 25'
```

All Doors

```yaml
      - type: custom:monster-card
        show_empty: false
        card:
          type: glance
          title: All doors
        filter:
          include:
            - device_class: door
```

All Windows

```yaml
      - type: custom:monster-card
        show_empty: false
        card:
          type: glance
          title: All Windows
        filter:
          include:
            - device_class: window
```

All Temperature Sensors

```yaml
      - type: custom:monster-card
        show_empty: false
        card:
          type: glance
          title: All doors
        filter:
          include:
            - device_class: temperature
```

**Comment by ciotlosm** [comment]
Considering `device_class` is just a normal attribute you should already be able to do this with monster card.

```
- type: custom:monster-card
  show_empty: false
  card:
    type: glance
    title: All doors
  filter:
    include:
      - attributes:
        device_class: door
```
