### ISSUE TITLE
Probably A Config Issue

### ISSUE THREAD

**Issue by mikegrb** [ciotlosm/custom-lovelace#2]
Should this config be valid? The state bit from the prior entity-filter wasn't mentioned for monster-card but I assume it supports similiar.
```yaml
    - type: "custom:monster-card"
      card:
        type: entities
        title: On
      filter:
        include:
          - domain: light
            state: 'on'
          - domain: switch
            state: 'on'
        exclude:
          - entity_id: "*undercounter*"
          - entity_id: switch.outside_front
          - entity_id: switch.outside_lights
          - entity_id: switch.dryer_switch
          - entity_id: switch.washer_switch
```

This generates an error:
`local/monster-card.js:52:46 Uncaught TypeError: Cannot read property 'filter' of undefined`

I assume this is just a configuration issue on my part but there wasn't sufficient examples for me to see what I might be doing wrong.

 EDIT:
Rereading the docs it sounds like entity_id, state, and domain may be mutually exclusive under filters. I tried the following but got the same error:
```yaml
        include:
          - state: 'on'
```

**Comment by mikegrb** [comment]
Looks like this might be a version mismatch issue. I'm not on the RC so the card's config is at this.config rather than at this._config where the code is looking, I assume that is where it is in the RC?

**Comment by ciotlosm** [comment]
I just tried your config with latest `monster-card` code (make sure you clear cache) and it worked:
```yaml
      - type: "custom:monster-card"
        card:
          type: entities
          title: "On"
        filter:
          include:
            - domain: light
              state: 'on'
            - domain: switch
              state: 'on'
          exclude:
            - entity_id: "*undercounter*"
            - entity_id: switch.outside_front
            - entity_id: switch.outside_lights
            - entity_id: switch.dryer_switch
            - entity_id: switch.washer_switch
```

I am running version 0.73.b6 of Home Assistant.
