### ISSUE TITLE
Custom color severity on bignumber

### ISSUE THREAD

**Issue by matisaul** [ciotlosm/custom-lovelace#20]
Maybe you could add a custom color into severity. For example:
```yaml
        - type: "custom:bignumber-card"
          title: Bedroom Temperature
          entity: sensor.temperature_bedroom
          severity:
            level1: 0
              - color: #FFF000
            level2: 15
              - color: #F0F0F0   
            level3: 25
              - color: #000000
```

Just an idea. This is good for setting colors on temperatures sensors (blue for cold levels, red in high temp.)
