### ISSUE TITLE
Thermostat Card does not show target temperature and operating mode (it does not change the color) with climate.nest

### ISSUE THREAD

**Issue by francesconazzaro** [ciotlosm/custom-lovelace#206]
Hi,
I've a Nest thermostat configured in my Home Assistant. I configured the thermostat card as follows:
```yaml
      - type: custom:thermostat-card
        title: Nest
        entity: climate.nest
        chevron_size: 100
        highlight_tap: true
        hvac:
          states:
            'Off': 'off'
            'Eco': 'eco'
            'Heating': 'heat'
          attribute: operation_mode
```
But the thermostat card does not show the target temperature. Furthermore when I increase or decrease the target temperature, by tapping on the widget, it starts always from 0 degrees.

Neither the operating mode is showed by changing color. 

I've seen that the attributes of climate.nest are:

```yaml
operation_list: off,heat,eco
away_mode: on
supported_features: 1153
max_temp: 32
friendly_name: Entryway (Termostato)
operation_mode: heat
current_temperature: 23.5
temperature: null
min_temp: 9
```

The other "attributes" are `sensor` or `bynary_sensor` like:

```yaml
binary_sensor.entryway_thermostat_termostato_has_leaf
sensor.entryway_thermostat_termostato_target
sensor.entryway_thermostat_termostato_hvac_state
```
this is my widget when the nest is heating:
![image](https://user-images.githubusercontent.com/9554021/46534687-5d96eb00-c8a9-11e8-83c3-5240284db98c.png)

**Comment by ciotlosm** [comment]
This is the most interesting @francesconazzaro 

The card uses `target_temperature` or `target_temperature_low` & `target_temperature_high` to set and maintain the target. So far the `climate` interface forced this to be mandatory, but your setup looks like it's working differently. 

Does it work properly with the default "climate" entity in the old /status interface?

While the component can have extra adjustments to accommodate your setup, I'd be reluctant to start implementation before understand if this is a normal setup or not. 

Also to fix the state issue, please remove:
```
          states:
            'Off': 'off'
            'Eco': 'eco'
            'Heating': 'heat'
```

The problem is your thermostat is reporting `operation_mode: heat` but you're forcing the card to try to map `heat` (from your Nest) through a mapping from 'Heating' which defaults then to 'off'. 

```js
hvac_state: config.hvac.states[hvac_state] || 'off',
```

The default setup for `states` is defined in the code (you can also define it yourself, but must do it correctly):

```js
    if (!cardConfig.hvac.states) cardConfig.hvac.states = { 'off': 'off', 'heat': 'heat', 'cool': 'cool', };
```

To explain better the mapping allows a thermostat that reports it's state as something weird like `H3ating` to still map to a valid value to display color by mapping it to `heat` used internally. 

```
'H3ating': 'heat'
```

**Comment by francesconazzaro** [comment]
Hi @ciotlosm thanks for the responsive answer!

I configured `climate.nest` with the official guide here https://www.home-assistant.io/components/nest/:
```
nest:
  client_id: my-client-id
  client_secret: my-client-secret
```

I removed the `states` entry as you suggest. Now I have a different "state issue". 
When the Nest is ON, it is always `orange-red`, also when it is not heating.
I guess because the `operation_mode` is `heat` also when the Nest is not heating. 
I'll resume:

- Nest On, Not heating (because the target temperature is below the ambient temperature): state is `heat`.
- Nest On, heating (because the target temperature is upper the ambient temperature): state is`heat`.
- Nest is Off: state is `off`.
- Nest is Eco: state is `eco`.

The color of the widget, in my case, should be set from the sensor `sensor.entryway_thermostat_termostato_hvac_state`.
This sensor has state `heating` when the Nest is actually heating, and it is `off` when the Nest is not heating.

**Comment by francesconazzaro** [comment]
I found 2 interesting documentation pages about Nest that i haven't seen before. And it seems exactly my situation:
https://www.home-assistant.io/components/binary_sensor.nest/
https://www.home-assistant.io/components/sensor.nest/
I have all those sensors in my Home Assistant instead of having them as `climate.nest` attributes.
But I don't know why I have those sensors because I did not configured them.

**Comment by Padre653** [comment]
I have the same issue with NEST.

It looks like the card looks for "operation_mode" to change the color of the display. In 'climate.XXX', the nest uses operation_mode to indicate if the HVAC is set to heating or cooling which would not allow the color to change as the furnace or A/C starts running. 
The nest uses 'hvac_state' to indicate the current state. The problem is, the Nest's 'climate.XXX' does not include this variable. The 'sensor.XXX_hvac_state' however, does. Is there anyway to pull the variable from the sensor?

**Comment by ciotlosm** [comment]
I will add it as an enhancement. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by francesconazzaro** [comment]
Hi @ciotlosm , are there any news on this?

**Comment by TurboTronix** [comment]
How do you get the state mode to work with Ecobee3? I used this code but no operation mode is displayed: 

```
- type: custom:thermostat-card
      title: Ecobee
      entity: climate.my_ecobee3
      chevron_size: 100
      hvac:
        states:
          'Off': 'off'
          'Cooling': 'cool'
          'Heating': 'heat'
        attribute: operation_mode
```
