### ISSUE TITLE
Excluded entities were showing up 

### ISSUE THREAD

**Issue by shreram** [ciotlosm/custom-lovelace#209]
I have the following snippet and expected entities in the 'exclude' section not to show up but they do. Am I missing something?

```
  - url: /local/monster-card.js?v=0.2.3
    type: js
```

```
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: Lights On
          show_header_toggle: false
        filter:
          include:
            - domain: light
              state: 'on'
            - domain: switch
              state: 'on'
          exclude:
            - entity_id: switch.garage_camera_night_mode
            - entity_id: switch.garage_camera_infrared_led
            - entity_id: switch.garage_camera_infrared_led_filter
            - entity_id: switch.garage_camera_motion_detection
            - entity_id: switch.garage_camera_rtsp_h264
            - entity_id: switch.garage_camera_rtsp_mjpeg
```

![screen shot 2018-10-14 at 5 50 33 pm](https://user-images.githubusercontent.com/16169720/46923184-d6005900-cfd9-11e8-9cd0-2f44186cc1bd.png)

**Comment by shreram** [comment]
My bad. There were other switch entities with no underscore in the name. I fixed them and everything works perfectly.

```
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: Lights On
          show_header_toggle: false
        filter:
          include:
            - domain: light
              state: 'on'
            - domain: switch
              state: 'on'
          exclude:
            - entity_id: '*garage_camera*'
            - entity_id: '*garagecamera*'
```
