### ISSUE TITLE
Cannot use a space in the "exclude state"

### ISSUE THREAD

**Issue by kernehed** [ciotlosm/custom-lovelace#215]
I cannot use a space in the exclude `state`, please see below.
I managed to fix it with a change of the state "Inget underlag" to "Inget".

Log and ui-lovelace.yaml below:

## Error in log:

`https://mydomain.duckdns.org:8123/local/lovelace/monster-card.js:37:32 Uncaught TypeError: _compare[operator] is not a function`

## My ui-lovelace.yaml:

```
    - type: custom:monster-card
      show_empty: false
      card:
        type: entities
        title: Pollennivåer
      filter:
        include:
          - entity_id: sensor.pollen_al
          - entity_id: sensor.pollen_alm
          - entity_id: sensor.pollen_salg_vide
          - entity_id: sensor.pollen_bjork
          - entity_id: sensor.pollen_bok
          - entity_id: sensor.pollen_ek
          - entity_id: sensor.pollen_grabo
          - entity_id: sensor.pollen_gras
          - entity_id: sensor.pollen_hassel
          - entity_id: sensor.pollen_salg_vide
        exclude:
          - state: "Inget underlag"
```
