### ISSUE TITLE
_getEntities is not defined for Monster card 

### ISSUE THREAD

**Issue by kylerw** [ciotlosm/custom-lovelace#22]
receiving
```
https://my.url.com/local/monster-card.js?v=1:60:33 Uncaught ReferenceError: _getEntities is not defined

```
 using:

```
      - type: "custom:monster-card"
        show_header_toggle: false
        show_empty: false
        card:
          title: Eating power
        filter:
          include:
            - domain: light
              entity_id: '*lamp'
              state: 'on'
            - domain: light
              state: 'on'
              entity_id: "*_level"
            - domain: switch
              state: 'on'
              entity_id: "*_switch"
            - domain: fan
              state: 'on'
          exclude:
            - domain: switch
              entity_id: "*modem*"
        

```

if I comment out the exclude, it works fine.
