### ISSUE TITLE
Alarm-card - Panel not showing

### ISSUE THREAD

**Issue by AcidSleeper** [ciotlosm/custom-lovelace#221]
Hey

Placed the .js file in the www-folder and placed  this code in my ui-lovelave.yaml
Running Home Assistant (Hassio) 0.82.1. 
Whats missing? Can see the title "Larm" but nothing in it.

```
resources:
  - url: /local/alarm_control_panel-card.js?v=1
    type: js

title: Home
views:
  - title: Home
    icon: mdi:home
    cards:
      - type: horizontal-stack
        cards:
          - type: entities
            entities:
              - sensor.ytterdorr_status
          - type: entity-filter
            entities:
              - sensor.sara_status
              - sensor.niclas_status
              - sensor.hugo_status

  - type: custom:alarm_control_panel-card
    entity: alarm_control_panel.larm
    show_keypad: true
    title: Larm
    style: '--alarm-color-disarmed: var(--label-badge-blue);'
    states:
      - arm_home
      - arm_away
    labels:
      ui.card.alarm_control_panel.code: Ange fyrsiffrig kod
      state.alarm_control_panel.arm_away: Away!!
```
