### ISSUE TITLE
entity-attributes-card Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by jvmonjo** [ciotlosm/custom-lovelace#222]
I'm running Home Assistant with hass.io

Monster Card is working Ok. But when I try to user entity-attributes-card lovelace will crash.
This is my configuration:

```yaml
- type: custom:entity-attributes-card
        title: Attributes Card
        heading_name: List
        heading_state: States
        filter:
          include:
            - key: media_player.*
```
The log system and Chrome dev tools are showing this error:

```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at _filterName (entity-attributes-card.js?v=0.1.1:21)
```
