### ISSUE TITLE
Excluded entities are still shown on the monster card.

### ISSUE THREAD

**Issue by niemyjski** [ciotlosm/custom-lovelace#227]
```yaml
      - type: custom:monster-card
        card:
          type: entities
          title: Lighting
        filter:
          include:
            - domain: light
```

I have several lights that are excluded from home assistant (zwave double added ge issue) and they are being included.
