### ISSUE TITLE
filter entities in a group?

### ISSUE THREAD

**Issue by Mariusthvdb** [ciotlosm/custom-lovelace#228]
HI 
Would it be possible to have the monster card filter all entities in a named group:

regular jinja template would be something like { % for g in state_attr('group.all_light_groups', 'entity_id') %}

```
  - type: custom:monster-card
    show_empty: false
    card:
      type: glance
      title: Lights On
    filter:
      include:
        - entity: { % for g in state_attr('group.all_light_groups', 'entity_id') %}
          state: 'on'
```

or maybe even simpler, only state the group which holds the entities, and use the group card?
thx!
