### ISSUE TITLE
Entities not showing up in order they are matched

### ISSUE THREAD

**Issue by thomasloven** [ciotlosm/custom-lovelace#23]
Example:
```yaml
    - type: custom:monster-card
      card:
        type: entities
      filter:
        include:
          - entity_id: sensor.automations_on
          - entity_id: sensor.automations_all
          - entity_id: automation.*
```
This will list all automations, followed by `sensor.automations_all` and `sensor.automations_on`.

I assume entities are displayed in alphabetical order. In order of matching by include list would be more intuitive and homogenized with how other cards work.
