### ISSUE TITLE
monster-card.js?v=1:112:7 TypeError: this.lastChild.setConfig is not a function

### ISSUE THREAD

**Issue by IVData** [ciotlosm/custom-lovelace#230]
Hi there,

I am getting this error running the latest version of monster-card.js on Home Assistant 0.84.6.

I have tried loading the page on Chrome and Firefox but get the same error. Here is my config:

```
- title: Packages
  cards:
    - type: custom:monster-card
      card:
        type: entites
        title: Packages
      filter:
        include:
          - domain: light
            state: 'on'
```
