### ISSUE TITLE
Uncaught SyntaxError: Identifier 'GroupCard' has already been declared

### ISSUE THREAD

**Issue by klaasnicolaas** [ciotlosm/custom-lovelace#232]
I got this error after loading the group card in lovelace. When opening the group card I also get a freeze in my browser.

This is my view:
```
id: automation
icon: mdi:home-automation
title: Automatisering
cards:
  # Toont alle automatiseringen
  - type: custom:group-card
    card:
      type: entities
      title: Automatisering
    group: group.all_automations
```
