### ISSUE TITLE
Filter Issue 

### ISSUE THREAD

**Issue by jokerigno** [ciotlosm/custom-lovelace#247]
Hi,

I have a strange issue using filter.

Here's my config:

```
          - type: custom:monster-card
            show_empty: false
            card:
              type: glance
              title: Ospiti
            filter:
              include:
                - entity_id: device_tracker.samsung_galaxy_s7_edge
                - entity_id: device_tracker.huawei_p8_lite_2017
                - entity_id: device_tracker.huawei_p8_lite_20172ff80
                - entity_id: device_tracker.jphone8p
                - entity_id: device_tracker.huawei_p_smart_ae6d9605e8
                  state: 'home'
```

The issue is that 2 device tracker (samsung_galaxy_s7_edge and huawei_p8_lite_2017) are shown in card also if status is not_home.
