### ISSUE TITLE
time filtering

### ISSUE THREAD

**Issue by mclaudiopt** [ciotlosm/custom-lovelace#251]
hello
is it possible to use monster card to show only timers that are running, like showing lights that are on?

```
type: 'custom:monster-card'
card:
  type: entities
filter:
  include:
    - entity_id: timer.wcrctoalheiro
    - entity_id: timer.1atoalheiro
    - entity_id: timer.suitetoalheiro
```
