### ISSUE TITLE
Wildcard in state for a filter?

### ISSUE THREAD

**Issue by murmelbahn** [ciotlosm/custom-lovelace#253]
Hi,

Im using a custom sensor which has a long string as a state which is sometimes different. I’m trying to show it in a monster card but it seems that a wildcard in “state” is not working:
```yaml

      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: "Müllabfuhr"
        filter:
          include:
            - entity_id: sensor.trash_subject*
              state: '*Abfuhr*'
```

Maybe it is possible to do it in another way? The sensor hase a long string as a state or nothing in it. Maybe there is a solution about the empty state field?

Thanks in advance.
