### ISSUE TITLE
Monster card doesn't correctly center map

### ISSUE THREAD

**Issue by i00** [ciotlosm/custom-lovelace#254]
I have the following:
```YAML
  - badges: []
    cards:
      - card:
          type: map
        filter:
          include:
            - attributes:
                source_type: gps
              entity_id: device_tracker.*
            - entity_id: zone.home
        type: 'custom:monster-card'
    icon: 'mdi:map'
    panel: true
    path: map
    title: Map
  - icon: 'mdi:map'
    panel: true
    path: map2
    title: Map2
    badges: []
    cards:
      - type: map
        entities:
          - entity: device_tracker.kris_alexander_bennett_phone
          - entity: zone.home

```
Map card is square,
Map2 card works fine and fills the page correctly
Happens when a page is in panel mode only
