### ISSUE TITLE
How can I use max cube thermostat card wit modes?

### ISSUE THREAD

**Issue by lpt2007** [ciotlosm/custom-lovelace#256]
HA attributes:

```
hvac_modes: auto 
current_temperature: 22.4 min_
temp: 4.5 
max_temp: 30.5 
temperature: 17 
preset_mode: null 
preset_modes: boost,manual,vacation 
friendly_name: HODNIK hallway_thermostat 
supported_features: 17
```

I try like this but I can see modes:

```
cards:
  - type: 'custom:thermostat-card'
    title: DNEVNA
    entity: climate.dnevna_livingroom_thermostat
    hvac:
      states:
        auto: auto
        manual: manual
        boost: boost
        vacation: vacation
      attribute: operation_mode
type: vertical-stack
```
