### ISSUE TITLE
Feature Request: Status panel/card

### ISSUE THREAD

**Issue by dshokouhi** [ciotlosm/custom-lovelace#28]
I was thinking it would be really neat if we could have a card that only shows up when entity-filter cards defined underneath have no entities and have `show_empty: false` defined.  Think of it as a user who wants to place all safety/security items in entity-filters.  Let's say I have a few different filters setup to show if the house detected leaks, smoke detectors going off, doors/windows open or unlocked, alarm tripped etc...   If none of those entities are shown the panel/card would show a green check mark or whatever the user defined.  This would allow for a quick check on the status of items with user friendly feedback that all is well.

**Comment by ciotlosm** [comment]
I think this should already be possible in the near future with `entity-filter` and `picture-entity`. 

See the sample I posted that is coming soon:

```yaml
     - type: entity-filter
        show_empty: false
        entities:
          - device_tracker.demo_paulus
        state_filter:
          - not_home
        card: 
          type: picture-entity
        ...........
```
