### ISSUE TITLE
FR: Option to filter on attributes.

### ISSUE THREAD

**Issue by ludeeus** [ciotlosm/custom-lovelace#3]
It would be great to ba able to filter entities based on attributes.
Some usecases for it:
I have a [custom_component to interact with ha-dockermon](https://github.com/custom-components/switch.hadockermon)
This component and many others add attributes with info to make them differentiate from the others:
![image](https://user-images.githubusercontent.com/15093472/42363431-f49cb966-80f7-11e8-9e6b-6920b8cae794.png)
with an attribute filter, users could easy filter on icon, component, version :)

For device_trackers there is a source attribute that would be good for filtering.

idea for filtering:
```yaml
- type: custom:monster-card
  card:
    type: glance
    title: Monster
  filter:
    include:
      - attribute: icon
        state: 'mdi:docker'
```

**Comment by ciotlosm** [comment]
Fixed in latest update. Config looks like:

```yaml
- type: custom:monster-card
  card:
    type: glance
    title: Monster
  filter:
    include:
      - domain: device_tracker
        attributes:
          battery: 53
          source_type: gps
```
Docs updated as well
