### ISSUE TITLE
Cannot get entity attributes card to work :(

### ISSUE THREAD

**Issue by tatunts** [ciotlosm/custom-lovelace#51]
Hello everyone! I've been trying for a couple of days without success get this useful custom card to work.

I want to create a cart just for the vacuum, but I get this:

![image](https://user-images.githubusercontent.com/25224882/42654865-807f5e64-85f0-11e8-9914-b80fa303ccae.png)

This is my code:

```yaml
- type: entities
  title: Aspirador
  show_header_toggle: no
  entities:
    - switch.aspirador
    - sensor.xiaomi_status
    - sensor.xiaomi_battery_level
    - input_select.estados_de_succao
    - input_select.zonas_de_aspiracao
    - type: custom:entity-attributes-card
      entity: vacuum.aspirador
      attributes:
        - key: vacuum.aspirador.do_not_disturb
          name: "Não perturbe"
        - key: vacuum.aspirador.cleaning_time
          name: "Tempo limpando"
        - key: vacuum.aspirador.cleaned_area
          name: "Área limpa"
        - key: vacuum.aspirador.main_brush_left
          name: "Escova principal"
        - key: vacuum.aspirador.side_brush_left
          name: "Escova lateral"
        - key: vacuum.aspirador.filter_left
          name: "Filtro"
```

Here is the list of all attributes:

```
status: Charging
battery_level: 100
battery_icon: mdi:battery-charging-100
fan_speed: Balanced
fan_speed_list: Quiet,Balanced,Turbo,Max
do_not_disturb: off
do_not_disturb_start: 22:00:00
do_not_disturb_end: 08:00:00
cleaning_time: 2
cleaned_area: 2
cleaning_count: 39
total_cleaned_area: 222
total_cleaning_time: 302
main_brush_left: 294
side_brush_left: 194
filter_left: 144
friendly_name: Aspirador
supported_features: 2047
```

Did I miss something here?

Thanks a lot!
