### ISSUE TITLE
Allow config for showing letters under keypad numbers

### ISSUE THREAD

**Issue by ciotlosm** [ciotlosm/custom-lovelace#78]
@davec proposed:

> See image of an example security alarm keypad here - https://goo.gl/images/8fKdwb 24
> 
> I was trying to suggest that like a PIN number for your credit card you may use a word that translates to numbers on a keypad, such as you would find on some alarm panels and most phones.
> Your access card is still a sequence of numbers, the letters on the buttons are simply a reminder of what key is what letter.

**Comment by gwww** [comment]
I have refactored the code I wrote to be able to show alpha. Work to do to actually show them. Needs some HTML and CSS to do so. On my github repo.

**Comment by ciotlosm** [comment]
@gwww would you be ok to merge the two cards?

**Comment by gwww** [comment]
Yes, please merge

**Comment by ciotlosm** [comment]
@gwww have a look here: https://github.com/ciotlosm/custom-lovelace/tree/alarm_refactor/alarm_control_panel-card

**Comment by vuiperez** [comment]
hi have input the files in WWW folder and on lovelace ui yaml i have this :+1: 

```
name: My Awesome Home

resources:
  - url: /local/monster-card.js?v=1
      type: js
  - url: /local/gauge-card.js?v=1
      type: js
  - url: /local/thermostat-card.js?v=1
      type: js


views:
    # The name of a view will be used as tab title.
    # Might be used for other things in the future.
  #- name: Home
  ######################################################################################################################  Home
  - title: Home
    icon: mdi:home-assistant
```

but love lace don't start, says "reload ui-lovelace.yaml"

what i'm doing wrong?

best regards
