### ISSUE TITLE
Card that lists all attributes for a sensor (without specifying them)

### ISSUE THREAD

**Issue by ghost** [ciotlosm/custom-lovelace#89]
A Plex sensor in home assistant produces individual attributes for each user watching. For example:

```yaml
{
  "jamesk - James Phone": "Hustle (2004) - S8 · E1 - Gold Finger",
  "James_k_wife - BedroomTV": "The Greatest Showman (2017)",
  "unit_of_measurement": "Watching",
  "friendly_name": "My Plex Server",
  "icon": "mdi:plex",
  "name": "Plex"
}
```

There are other similar sensors where the attribute names aren't fixed, and there are a potentially unknown (large) number of them, so you can't specify them in yaml. Thus I'd like a card that is able to list all attributes for a given entity (with the ability to filter out some specified exclusions, such as friendly name), but without having to list it the attribute names in yaml, since this isn't possible under the circumstances. (In the above example, the could be a third, fourth, fifth person also using the Plex server, theoretically).
